#
# Copyright (c) 2012-2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation

name: Docker Build
on:
  workflow_dispatch:
  push:
    branches: [ master ]
jobs:
  build-push:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.default == false }}
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64]
        default: [true]
        # include:
        #   - platform: linux/arm64
        #     default: false
        #   - platform: linux/ppc64le
        #     default: false
    steps:
    - name: Checkout che-machine-exec source code
      uses: actions/checkout@v2
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"       
    - name: Login to quay.io
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io
    - name: Check docker build
      uses: docker/build-push-action@v2
      with:
        file: build/dockerfiles/Dockerfile
        platforms: ${{ matrix.platform }}
        push: true
        tags: |
          quay.io/rahulssv/che-machine-exec:nightly
          quay.io/rahulssv/che-machine-exec:${{ steps.vars.outputs.sha_short }}
